### ISSUE TITLE
License please!

### ISSUE THREAD

**Issue by realvictorprm** [Bilka2/Subterrain#1]
Please give us any information about with which License this is released on github so one knows whether it's safe to publish an own variation of the mod.

**Comment by Bilka2** [comment]
The license is included in the mod and here on github and the mod portal also lists it. This has been the case even before I forked it.

**Comment by realvictorprm** [comment]
Sorry I've described it worse. Is it possible to make it appear in the tab of github too?

**Comment by Bilka2** [comment]
No, forked repositories cannot display the license [like this](https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/).

**Comment by realvictorprm** [comment]
OK, thanks for the info @Bilka2 ! 👍
