### ISSUE TITLE
Upgrade Planner and Subteranean causing crashes now

### ISSUE THREAD

**Issue by jarquafelmu** [Bilka2/Subterrain#2]
Started yesterday or 0.16.26. When upgrade planner attempts to upgrade a section that contains a subterranean belt part the game crashes with the following error:

![upgrade planner](https://user-images.githubusercontent.com/5807272/36764955-4b04224c-1bec-11e8-83da-2eea8b86de66.PNG)

Here is a link to the issue in their github: [Issue 2](https://github.com/Klonan/upgrade-planner/issues/2)

**Comment by Bilka2** [comment]
It wont error now, but the belts dont connect. I'm assuming that this is an issue with the base game, so I'll make a bug report.

Edit: Nevermind, my fault. I think the belt upgrading should even work cost-wise, so have fun with the upgrade planner :).
